version: "3.7"

services:
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "@P@ssw0rd02"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    volumes:
      - data:/var/opt/mssql
  movieticket:
    build:
      context: .
      dockerfile: src/server/MovieTicket.Api/Dockerfile
    environment:
      ConnectionStrings__db: Server=db;Database=movie_ticket;Encrypt=false;User Id=sa;Password=@P@ssw0rd02;
      Identity__Url: identityserver:8081
    ports:
      - "8080:80"
    depends_on:
      - db
  identityserver:
    build:
      context: .
      dockerfile: src/server/MovieTicket.IdentityServer/Dockerfile
    environment:
        ConnectionStrings__db: Server=db;Database=movie_user;Encrypt=false;User Id=sa;Password=@P@ssw0rd02;
    ports:
      - "8081:80"
    depends_on:
      - db


volumes:
  data: