version: "3.7"

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    networks:
      movie-network:
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "@P@ssw0rd02"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - data:/var/opt/mssql
    networks:
      movie-network:


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    restart: always
    networks:
      - movie-network


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - 9092:9092
    restart: always
    networks:
      - movie-network

  notificationservice:
    #image: chinhval/movieticketnotification
    build:
      context: ..
      dockerfile: src/server/Notification/Notification.Api/Dockerfile
    container_name: notificationservice
    environment:
      - ConnectionStrings__db=Server=db;Database=Jobs;Encrypt=false;User Id=sa;Password=@P@ssw0rd02;
      - Kafka__Url=kafka:9092
      - Redis__Url=redis:6379
    ports:
      - "8096:80"
    
    depends_on:
      - db
      - kafka
    
    labels:
      - "com.centurylinklabs.watchtower.enbale=true"
    volumes:
      - ./sercet/android-5e2d0-firebase-adminsdk-p2ikp-adbe0b9280.json:/app/android-5e2d0-firebase-adminsdk-p2ikp-adbe0b9280.json
    networks:
      movie-network:


  appgateway:
    image: chinhval/movieticketappgateway
    container_name: appgateway
    ports:
      - "4000:80"
    environment:
      #- ReverseProxy__Clusters__api-auth__Destinations__destination1__Address=http://identityservermanagement
      - ReverseProxy__Routes__clientapi__ClusterId=client-api
      - ReverseProxy__Routes__clientapi__Match__Path=/client-api/{**remainder}
      - ReverseProxy__Routes__clientapi__Transforms_0__PathRemovePrefix=/client-api
      - ReverseProxy__Routes__clientapi__Transforms_1__PathPrefix=/api

      - ReverseProxy__Routes__clientidentity__ClusterId=client-identity
      - ReverseProxy__Routes__clientidentity__Match__Path=/client-identity/{**remainder}
      - ReverseProxy__Routes__clientidentity__Transforms_0__PathRemovePrefix=/client-identity
      - ReverseProxy__Routes__clientidentity__Transforms_1__PathPrefix=/

      - ReverseProxy__Routes__adminapi__ClusterId=admin-api
      - ReverseProxy__Routes__adminapi__Match__Path=/admin-api/{**remainder}
      - ReverseProxy__Routes__adminapi__Transforms_0__PathRemovePrefix=/admin-api
      - ReverseProxy__Routes__adminapi__Transforms_1__PathPrefix=/api

      - ReverseProxy__Routes__adminidentity__ClusterId=admin-identity
      - ReverseProxy__Routes__adminidentity__Match__Path=/admin-identity/{**remainder}
      - ReverseProxy__Routes__adminidentity__Transforms_0__PathRemovePrefix=/admin-identity
      - ReverseProxy__Routes__adminidentity__Transforms_1__PathPrefix=/

      - ReverseProxy__Routes__notificationapi__ClusterId=notification-api
      - ReverseProxy__Routes__notificationapi__Match__Path=/notification-api/{**remainder}
      - ReverseProxy__Routes__notificationapi__Transforms_0__PathRemovePrefix=/notification-api
      - ReverseProxy__Routes__notificationapi__Transforms_1__PathPrefix=/




      - ReverseProxy__Routes__adminui__ClusterId=admin-api
      - ReverseProxy__Routes__adminui__Match__Path=/{**catch-all}
      - ReverseProxy__Routes__adminui__Transforms_1__PathPrefix=/



      - ReverseProxy__Routes__assets__ClusterId=admin-api
      - ReverseProxy__Routes__assets__Match__Path=/assets/{**remainder}
      - ReverseProxy__Routes__assets__Transforms_0__PathRemovePrefix=/assets
      - ReverseProxy__Routes__assets__Transforms_1__PathPrefix=/assets


      - ReverseProxy__Clusters__client-api__Destinations__destination1__Address=http://movieticketclient
      - ReverseProxy__Clusters__client-identity__Destinations__destination1__Address=http://identityserverclient
      - ReverseProxy__Clusters__admin-api__Destinations__destination1__Address=http://movieticketmanagement
      - ReverseProxy__Clusters__admin-identity__Destinations__destination1__Address=http://identityservermanagement
      - ReverseProxy__Clusters__notification-api__Destinations__destination1__Address=http://notificationservice
    labels:
      - "com.centurylinklabs.watchtower.enbale=true"
    
    depends_on:
      - notificationservice
    networks:
      movie-network:

volumes:
  data:
networks:
  movie-network: