version: "3.7"


services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    restart: always
    networks:
      - movie-ticket


  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    restart: always
    networks:
      - movie-ticket
  db: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: movie_db
    environment:
      SA_PASSWORD: "@P@ssw0rd02"
      MSSQL_PID: "Standard"
      ACCEPT_EULA: "Y"
      TZ: Asia/Ho_Chi_Minh
    restart: always
    ports:
      - 1433:1433
    volumes:
      - data:/var/opt/mssql
    networks:
      - movie-ticket
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    networks:
      - movie-ticket
volumes:
  data:
networks:
  movie-ticket: