version: "3.7"


services:
  db: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: movie_db
    environment:
      SA_PASSWORD: "@P@ssw0rd02"
      MSSQL_PID: "Standard"
      ACCEPT_EULA: "Y"
      TZ: Asia/Ho_Chi_Minh
    ports:
      - 1433:1433
    volumes:
      - data:/var/opt/mssql
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
volumes:
  data: