name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:

jobs:
  main:
    name: Build dotnet api

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Context
        uses: actions/checkout@v4
        
      - name: Build app Docker image
        shell: bash
        run: docker build . -t myapp -f ./src/server/MovieTicket.Api/Dockerfile
        
        
        
        
  mobile:
    name: Build file apk
    runs-on: ubuntu-latest
    env:
      ANDROID_API_LEVEL: 30
      ANDROID_BUILD_TOOLS_VERSION: 30.0.3
      ANDROID_ABI: x86_64

    steps:
      - uses: actions/checkout@v4
        
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('src/client/mobile/**/*.gradle*', 'src/client/mobile/**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-