name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:

jobs:
  main:
    name: Build server for movie

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Context
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image for admin server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/server/Management/MovieTicketManagement.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_API_SERVER_NAME}}:latest
      - name: Build and push Docker image for admin identity server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/server/Management/MovieTicketManagement.IdentityServer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_IDENTITY_SERVER_NAME}}:latest
          
        
      - name: Build and push Docker image for client server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/server/Client/MovieTicketClient.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_API_CLIENT_NAME}}:latest
      - name: Build and push Docker image for client identity server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/server/Client/MovieTicketClient.IdentityServer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_IDENTITY_CLIENT_NAME}}:latest
      - name: Build and push Docker image app gateway server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/server/Proxy/MovieTicket.AppGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_APPGATEWAY_NAME}}:latest
      - name: Build and push Docker image app notification server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/server/Notification/Notification.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NOTIFICATION_NAME}}:latest
        
        
 